//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpTicket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int ID_usuario { get; set; }
        public string nombres { get; set; }
        public string correo { get; set; }
        public string codigo { get; set; }
        public string contraseña { get; set; }
        public string rol_creacion { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string token { get; set; }
    }
}
